matrix:
  include:
  - os: linux                                                                   
    python: 3.6                                                                 
    env:
      - PYTHON_VERSION=3.6
      - INSTALL_METHOD=src
  - os: linux                                                                   
    python: 3.6                                                                 
    env:
      - PYTHON_VERSION=3.6
      - INSTALL_METHOD=pip
  - os: linux
    python: 3.7
    env:
      - PYTHON_VERSION=3.7
      - INSTALL_METHOD=src
  - os: linux
    python: 3.7
    env:
      - PYTHON_VERSION=3.7
      - INSTALL_METHOD=pip
  - os: linux
    python: 3.8
    env:
      - PYTHON_VERSION=3.8
      - INSTALL_METHOD=src
  - os: linux
    python: 3.8
    env:
      - PYTHON_VERSION=3.8
      - INSTALL_METHOD=pip
  - os: linux
    python: 3.9
    env:
      - PYTHON_VERSION=3.9
      - INSTALL_METHOD=src
  - os: linux
    python: 3.9
    env:
      - PYTHON_VERSION=3.9
      - INSTALL_METHOD=pip
  - os: osx                                                                     
    language: generic                                                           
    env:                                                                        
      - PYTHON_VERSION=3.6
      - INSTALL_METHOD=src
  - os: osx                                                                     
    language: generic                                                           
    env:                                                                        
      - PYTHON_VERSION=3.6
      - INSTALL_METHOD=pip
  - os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.7
      - INSTALL_METHOD=src
  - os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.7
      - INSTALL_METHOD=pip
  - os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.8
      - INSTALL_METHOD=src
  - os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.8
      - INSTALL_METHOD=pip
  - os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.9
      - INSTALL_METHOD=src
  - os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.9
      - INSTALL_METHOD=pip

compiler:
    - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == linux ]; then MINICONDAVERSION="Linux"; else MINICONDAVERSION="MacOSX"; fi
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-$MINICONDAVERSION-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create --yes -n py_entitymatching_test_env python=$PYTHON_VERSION --no-default-packages
  - python --version  

install: TRAVIS_OS_NAME="$TRAVIS_OS_NAME" ./ci-scripts/install-${INSTALL_METHOD}.sh

script: ./ci-scripts/test-from-${INSTALL_METHOD}.sh
