
environment:
  global:
    # Appveyor machines now come with miniconda
    CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"

  matrix:

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      APP_CONDA_PY: "2.7.18"

    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      APP_CONDA_PY: "3.5.10"
      
    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      APP_CONDA_PY: "3.6.12"

    - PYTHON: "C:\\Python37_64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      APP_CONDA_PY: "3.7.9"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
  - SET PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\Scripts;%PATH%

  # Don't install from requirements-pip.txt, python-coveralls has broken dependencies on windows it seems.
  - conda install --yes setuptools nose numpy pip coverage scipy pandas pyparsing six scikit-learn Cython cloudpickle joblib ipython
  - pip install -r requirements.txt
  - if %PYTHON_VERSION%==3.5 (pip install PyQt5)
  - if %PYTHON_VERSION%==3.6 (pip install PyQt5)
  - if %PYTHON_VERSION%==3.7 (pip install PyQt5)
  - python setup.py build_ext --inplace

build: false

test_script:
  # Nosetests take care of unit tests
  # Behave runs the example scripts and tries to verify if it produces the right output
  - nosetests
  #- behave --tags ~@skip # Everything without the tag @skip

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!
  #- coverage report
  # coveralls
